routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('index');

Route::get('/new', function () {
    return view('new');
})->name('new');

Route::get('/welcome', function () {
    return view('welcome');
})->name('welcome');

Route::get('/about', function () {
    return view('about');
})->name('about');

Route::get('/galls', function () {
    return view('galls');
})->name('galls');

Route::get('/gall-inner', function () {
    return view('gall-inner');
})->name('gall-inner');

Route::get('/orderservice', function () {
    return view('orders');
})->name('orders');

Route::get('/service-inner', function () {
    return view('service-inner');
})->name('service-inner');

Route::resource('order', OrderController::class);

Route::get('/services', 'ServiceController@index')->name('services');
Route::get('/services/{id}', 'ServiceController@show')->name('services/{id}');

Route::middleware(['role:admin'])->prefix('admin_panel')->group (function () {
      Route::get('/', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('homeAdmin');
      Route::resource('documents', \Admin\DocumentsController::class);
      Route::resource('service', \Admin\ServiceController::class);
      Route::resource('project', \Admin\ProjectController::class);
      Route::resource('user', \Admin\UserController::class);    
      Route::resource('order', OrderController::class); 

});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['role:writer'])->resource('cabinet', CabinetController::class);      

app/Models/Documents.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Documents extends Model
{
    use HasFactory;
}

app/Http/Controllers/Admin/DocumentsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Documents;
use Illuminate\Http\Request;
use Storage;

class DocumentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $documents = Documents::orderBy('created_at', 'desc')->get();
        return view('admin.documents.index', [
        'documents' => $documents
      ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.documents.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $new_document = new Documents ();
        $new_document->DocName = $request->DocName;
        $new_document->DocUrl = $request->DocUrl; //Storage::put('public', $request->DocUrl);
        $new_document->save();

        return redirect()->back()->withSuccess('Документ был успешно добавлен');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Documents  $documents
     * @return \Illuminate\Http\Response
     */
    public function show(Documents $documents)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Documents  $documents
     * @return \Illuminate\Http\Response
     */
    public function edit(Documents $documents)
    {
        return view('admin.documents.edit', [
          'documents'=>$documents
    ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Documents  $documents
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Documents $documents)
    {
      $documents->DocName = $request->DocName;
      $documents->DocUrl = $request->DocUrl;
      $documents->save();

      return redirect()->back()->withSuccess('Документ был успешно обновлен');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Documents  $documents
     * @return \Illuminate\Http\Response
     */
    public function destroy($documents)
    {
        Documents::find($documents)->delete();
        
        return redirect()->back()->withSuccess('Документ был успешно удален');
    }
}

resources/views/admin/documents/create.blade.php
@extends ('layouts.admin_layout')

@section('title', 'Добавить документ')

@section('content')
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0">Добавить документ</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
            </div>
        @endif
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
    <div class="card card-primary">
       <div class="card-header">
         <h3 class="card-title"></h3>
       </div>
       <!-- /.card-header -->
       <!-- form start -->
       <form action="{{route ('documents.store')}}" method="POST">
         @csrf
         <div class="card-body">
           <div class="form-group">
             <label for="exampleInputEmail1">Название документа</label>
             <input type="text" name="DocName" class="form-control" id="exampleInputEmail1" placeholder="Введите название документа" required >
           </div>
           <div class="form-group">
             <label for="exampleInputEmail1">Ссылка на файл документа</label>
             <input type="text" name="DocUrl" class="form-control" id="exampleInputEmail1" placeholder="Загрузите ссылку на документ" required >
           </div>
           </div>
         </div>
         <!-- /.card-body -->
         <div class="card-footer">
           <button type="submit" class="btn btn-primary">Добавить</button>
         </div>
       </form>
     </div>
  </div>
</div>
</div>
</section>
<!-- /.content -->
@endsection

resources/views/admin/documents/edit.blade.php
@extends ('layouts.admin_layout')

@section('title', 'Редактировать документ')

@section('content')
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0">Редактировать  документ: {{ $documents['DocName'] }}</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
            </div>
        @endif
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
    <div class="card card-primary">
       <div class="card-header">
         <h3 class="card-title"></h3>
       </div>
       <!-- /.card-header -->
       <!-- form start -->
       <form action="{{route ('documents.update', $documents['id'] )}}" method="POST">
         @csrf
         @method('PATCH')
         <div class="card-body">
           <div class="form-group">
             <label for="exampleInputEmail1">Название документа</label>
             <input type="text" value="{{ $documents['DocName'] }}" name="DocName" class="form-control" id="exampleInputName" placeholder="Введите название документа" required >
           </div>
           <div class="form-group">
             <label for="exampleInputFile">Добавить файл</label>
             <div class="input-group">
               <div class="custom-file">
                 <input type="file" name="DocUrl" class="custom-file-input" id="exampleInputFile">
                 <label class="custom-file-label" for="exampleInputFile">Прикрепите файл</label>
               </div>
               <div class="input-group-append">
                 <span class="input-group-text">Прикрепить</span>
               </div>
             </div>
           </div>
         </div>
         <!-- /.card-body -->
         <div class="card-footer">
           <button type="submit" class="btn btn-primary">Обновить</button>
         </div>
       </form>
     </div>
  </div>
</div>
</div>
</section>
<!-- /.content -->
@endsection

resources/views/admin/documents/index.blade.php
@extends ('layouts.admin_layout')

@section('title', 'Все документы')

@section('content')
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0">Все документы</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
            </div>
        @endif
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 1%">
                          #
                      </th>
                      <th style="width: 20%">
                          Название документа
                      </th>

                  </tr>
              </thead>
              <tbody>
                @foreach ($documents as $element)
                    <td>
                        {{ $element ['id']}}
                    </td>
                    <td>
                        <a>
                            {{ $element['DocName']}}
                        </a>
                        <br/>
                        <small>
                            {{ $element ['DocUrl']}}
                        </small>
                    </td>
                    <td class="project-actions text-right">
                      <!--  <a class="btn btn-info btn-sm" href="{{route ('documents.edit', $element['id'] )}}">
                            <i class="fas fa-pencil-alt">
                            </i>
                            Редактировать
                        </a> -->
                        <form action="{{ route('documents.destroy', $element['id']) }}" method="POST"
                            style="display: inline-block">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-sm delete-btn">
                                <i class="fas fa-trash">
                                </i>
                                Удалить
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach

              </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
</div>
</section>
<!-- /.content -->
@endsection