routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('index');

Route::get('/new', function () {
    return view('new');
})->name('new');

Route::get('/welcome', function () {
    return view('welcome');
})->name('welcome');

Route::get('/about', function () {
    return view('about');
})->name('about');

Route::get('/galls', function () {
    return view('galls');
})->name('galls');

Route::get('/gall-inner', function () {
    return view('gall-inner');
})->name('gall-inner');

Route::get('/orderservice', function () {
    return view('orders');
})->name('orders');

Route::get('/service-inner', function () {
    return view('service-inner');
})->name('service-inner');

Route::resource('order', OrderController::class);

Route::get('/services', 'ServiceController@index')->name('services');
Route::get('/services/{id}', 'ServiceController@show')->name('services/{id}');

Route::middleware(['role:admin'])->prefix('admin_panel')->group (function () {
      Route::get('/', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('homeAdmin');
      Route::resource('documents', \Admin\DocumentsController::class);
      Route::resource('service', \Admin\ServiceController::class);
      Route::resource('project', \Admin\ProjectController::class);
      Route::resource('user', \Admin\UserController::class);    
      Route::resource('order', OrderController::class); 

});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['role:writer'])->resource('cabinet', CabinetController::class);      

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    
    public function projects()
    {
        return $this->hasMany('App\Models\Project', 'UserID');
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('created_at', 'desc')->get();
        $roles = Role::orderBy('created_at', 'desc')->get();
        return view('admin.user.index', [
            'users' => $users,
            'roles' => $roles
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::orderBy('created_at', 'desc')->get();
        return view('admin.user.create', [
            'users' => $users
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($user)
    {
        User::find($user)->delete();

        return redirect()->back()->withSuccess('Пользователь был успешно удален');
    }
}

resources/views/admin/user/create.blade.php
@extends ('layouts.admin_layout')

@section('title', 'Добавить пользователя')

@section('content')
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0">Добавить пользователя</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
            </div>
        @endif
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
    <div class="card card-primary">
       <div class="card-header">
         <h3 class="card-title"></h3>
       </div>
       <!-- /.card-header -->
       <!-- form start -->
       <form action="{{route ('project.store')}}" method="POST">
         @csrf
         <div class="card-body">
           <div class="form-group">
             <label for="exampleInputEmail1">Название проекта</label>
             <input type="text" name="ProjectName" class="form-control" id="exampleInputEmail1" placeholder="Введите название проекта" required >
           </div>
           <div class="form-group">
             <label for="exampleInputEmail1">Дата начала проекта</label>
             <input type="date" name="ProjectBegin" value="Y-m-d" class="form-control" id="exampleInputEmail1" placeholder="Введите дату начала проекта" required >
           </div>
           <div class="form-group">
             <label for="exampleInputEmail1">Дата утверждения дизайна</label>
             <input type="date" name="ProjectApprove" value="Y-m-d" class="form-control" id="exampleInputEmail1" placeholder="Введите дату утверждения дизайна" required >
           </div>
           <div class="form-group">
             <label for="exampleInputEmail1">Дедлайн проекта</label>
             <input type="date" name="ProjectDeadline" value="Y-m-d" class="form-control" id="exampleInputEmail1" placeholder="Введите дедлайн проекта" required >
           </div>
           <div class="form-group">
             <label for="exampleInputEmail1">Статус проекта</label>
             <input type="text" name="ProjectStatus" class="form-control" id="exampleInputEmail1" placeholder="Введите статус проекта" required >
           </div>      
           <div class="form-group">
             <label for="exampleInputEmail1">Менеджер проекта</label>
             <input type="text" name="ProjectManager" class="form-control" id="exampleInputEmail1" placeholder="Введите имя Менеджера проекта" required >
           </div>        
           <div class="form-group">
             <label for="exampleInputEmail1">Ссылка на файлы проекта </label>
             <input type="text" name="ProjectUrl" class="form-control" id="exampleInputEmail1" placeholder="Загрузите ссылку с файлами на проект" required >
           </div>
           <div class="form-group">
             <label for="exampleInputEmail1">Выберите клиента</label>
           <select name='UserID' class="custom-select form-control-border border-width-2" id="exampleSelectBorderWidth2" required>
           @foreach ($users as $user)
              <option value="{{ $user['id']}}">{{ $user['name']}}</option>
          @endforeach
          </select>
         </div>
           </div>
         </div>
         <!-- /.card-body -->
         <div class="card-footer">
           <button type="submit" class="btn btn-primary">Добавить</button>
         </div>
       </form>
     </div>
  </div>
</div>
</div>
</section>
<!-- /.content -->
@endsection

resources/views/admin/user/edit.blade.php
@extends ('layouts.admin_layout')

@section('title', 'Редактировать проект')

@section('content')
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0">Редактировать  проект: {{ $project['ProjectName'] }}</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
            </div>
        @endif
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
    <div class="card card-primary">
       <div class="card-header">
         <h3 class="card-title"></h3>
       </div>
       <!-- /.card-header -->
       <!-- form start -->
       <form action="{{route ('project.update', $project['id'] )}}" method="POST">
         @csrf
         @method('PATCH')
         <div class="card-body">
           <div class="form-group">
             <label for="exampleInputEmail1">Название проекта</label>
             <input type="text" name="ProjectName" value="{{$project['ProjectName']}}" class="form-control" id="exampleInputEmail1" placeholder="Введите название проекта" required >
           </div>
           <div class="form-group">
             <label for="exampleInputEmail1">Дата начала проекта</label>
             <input type="date" name="ProjectBegin" value="{{$project['ProjectBegin']}}" class="form-control" id="exampleInputEmail1" placeholder="Введите дату начала проекта" required >
           </div>
           <div class="form-group">
             <label for="exampleInputEmail1">Дата утверждения дизайна</label>
             <input type="date" name="ProjectApprove" value="{{$project['ProjectApprove']}}" class="form-control" id="exampleInputEmail1" placeholder="Введите дату утверждения дизайна" required >
           </div>
           <div class="form-group">
             <label for="exampleInputEmail1">Дедлайн проекта</label>
             <input type="date" name="ProjectDeadline" value="{{$project['ProjectDeadline']}}" class="form-control" id="exampleInputEmail1" placeholder="Введите дедлайн проекта" required >
           </div>
           <div class="form-group">
             <label for="exampleInputEmail1">Статус проекта</label>
             <input type="text" name="ProjectStatus" value="{{$project['ProjectStatus']}}" class="form-control" id="exampleInputEmail1" placeholder="Введите статус проекта" required >
           </div>      
           <div class="form-group">
             <label for="exampleInputEmail1">Менеджер проекта</label>
             <input type="text" name="ProjectManager" value="{{$project['ProjectManager']}}" class="form-control" id="exampleInputEmail1" placeholder="Введите имя Менеджера проекта" required >
           </div>        
           <div class="form-group">
             <label for="exampleInputEmail1">Ссылка на файлы проекта </label>
             <input type="text" name="ProjectUrl" value="{{$project['ProjectUrl']}}" class="form-control" id="exampleInputEmail1" placeholder="Загрузите ссылку с файлами на проект" required >
           </div>
           <div class="form-group">
             <label for="exampleInputEmail1">Выберите клиента</label>
           <select name='UserID' class="custom-select form-control-border border-width-2" id="exampleSelectBorderWidth2" required>
           @foreach ($user as $element)
                    <option value=" {{ $element['id'] }} " @if ( $element['id'] ) == $project['UserID']) selected @endif>{{ $element['UserID']}}</option>
          @endforeach
          </select>
         </div>
           </div>
         </div>
         <!-- /.card-body -->
         <div class="card-footer">
           <button type="submit" class="btn btn-primary">Обновить</button>
         </div>
       </form>
     </div>
  </div>
</div>
</div>
</section>
<!-- /.content -->
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin_layout')

<blade
    section|(%26%2339%3Btitle%26%2339%3B%2C%20%26%2339%3B%D0%92%D1%81%D0%B5%20%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D0%B8%26%2339%3B)%0D />

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Все пользователи</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                @if(session('success'))
                    <div class="alert alert-success" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
                    </div>
                @endif
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Имя пользователя
                            </th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach($users as $element)
                        <tr>
                            <td>
                                {{ $element['id'] }}
                            </td>
                            <td>
                                <a>
                                    {{ $element['name'] }}
                                </a>
                                <br />
                                <small>
                                    {{ $element['email'] }}
                                </small>
                                @foreach($roles as $element)
                                    <small>
                                        {{ $element['name'] }}
                                    </small>
                                    @endforeach
                      <!--      </td>
                              <td class="project-actions text-right">
                               <a class="btn btn-info btn-sm"
                                    href="{{ route ('user.edit', $element['id'] ) }}">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Редактировать
                                </a>
                                <form
                                    action="{{ route('user.destroy', $element['id']) }}"
                                    method="POST" style="display: inline-block">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger btn-sm delete-btn">
                                        <i class="fas fa-trash">
                                        </i>
                                        Удалить
                                    </button>
                                </form>
                            </td> 
                            </tr> -->
                        @endforeach
                        
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</section>
<!-- /.content -->
@endsection